title: "博客"
description: "路漫漫."

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: "zzkuai"
email: "zzkuai@gmail.com"
social:
  github: "zzkuai"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
